# Generated by Django 5.1.1 on 2024-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_ticket_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
